plugins {
    id 'java-platform'
    id 'internal.java' apply false
    id 'internal.java-library' apply false
}

allprojects {
    group = 'net.bdk.util'
}

subprojects {
    apply plugin: 'internal.java'
    apply plugin: 'internal.java-library'

    version = '1.0-SNAPSHOT' // todo: pull from ref name when rel branch or when tag (after validating major number same)

    spotbugs {
        excludeFilter = file(".spotbugs/exclude.xml")
    }
}

dependencies {
    constraints {
        api("project:leetcode-demo-util")
    }
}